version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      test:
          ipv4_address: "172.18.0.10"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: 'DOCKER://172.18.0.11:9092'
      KAFKA_ADVERTISED_LISTENERS: 'DOCKER://172.18.0.11:9092'
      KAFKA_CREATE_TOPICS: "test-topic:1:1"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'DOCKER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'DOCKER'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      test:
          ipv4_address: "172.18.0.11"
networks:
  test:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16